@startuml mcd comics engineering

package comics_db {
    class Users {
        *id: id
        email: text
        password: hash
        created_at: datetime
        modified_at: datetime
    }

    class Books {
        *id: id
        name: text
        desc: longtext
        number: number
        created_at: datetime
        modified_at: datetime
    }

    class Editions {
        *id: id
        -publisher_id: id
        -book_id: id
        -added_by: id
        isbn: text
        ean: text
        url: text
        img_url: text
        created_at: datetime
        modified_at: datetime
    }
    note top: isbn and ean treated, no "-"

    class Series {
        *id: id
        name: text
        ongoing: boolean
        oneshot: boolean
        nvolumes: text
        created_at: datetime
        modified_at: datetime
    }
    note top: number can be null

    class Publishers {
        *id: id
        name: text
        created_at: datetime
        modified_at: datetime
    }
	
	class BookOwnership {
        - *user_id: id
        - *book_id: id
        read: boolean
        gift: boolean
        buy_price: float
        date: datetime
    }
    note top: composed pkey

    class Wishlist {
        - *user_id: id
        - *book_id: id
    }
    note top: composed pkey
}

package comics_prices_db {
    class Book {
        *id: id
        retail_prices: [
            { source: text, price: float, date: datetime }
        ]
        second_hand_prices: [
            { source: text, price: float, date: datetime }
        ]
    }
}

BookOwnership "*" --> "1" comics_db.Books
BookOwnership "*" --> "1" Users

Wishlist "*" --> "1" comics_db.Books
Wishlist "*" --> "1" Users

Editions "*" --> "1" comics_db.Books
Editions "*" --> "1" Publishers
Editions "*" --> "1" Users

comics_db.Books "*" --> "1" Series

comics_db.Books ..> comics_prices_db.Book

@enduml