/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.stuten.vps;

import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;

import dev.stuten.vps.web.Routes;
import io.javalin.Javalin;
import io.javalin.json.JavalinJackson;

public class App {

    public static void main(String[] args) {

        int port = Integer.parseInt(System.getenv("APP_PORT"));
        String allowedOrigin = System.getenv("CORS_ALLOWED_ORIGIN");

        Javalin app = Javalin.create(config -> {
            config.http.defaultContentType = "application/json";
            // Jackson modules
            config.jsonMapper(new JavalinJackson().updateMapper(mapper -> {
                mapper.registerModule(new Jdk8Module());
                mapper.registerModule(new JavaTimeModule());
            }));
            // CORS policy
            config.bundledPlugins.enableCors(cors -> {
                cors.addRule(it -> {
                    it.allowHost(allowedOrigin);
                    it.allowCredentials = true;
                    it.exposeHeader("Authorization");
                });
            });
            config.router.ignoreTrailingSlashes = true;
        });

        app.before(ctx -> {
            if (ctx.method().toString().equals("OPTIONS")) {
                ctx.header("Access-Control-Allow-Origin", allowedOrigin);
                ctx.header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
                ctx.header("Access-Control-Allow-Headers", "Content-Type, Authorization");
                ctx.header("Access-Control-Allow-Credentials", "true");
                ctx.status(200);
                ctx.skipRemainingHandlers();
            }
        });

        Routes.register(app);

        // Handle OPTIONS preflight requests
        app.options("/*", ctx -> ctx.status(204));

        app.start(port);
    }
}
