/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.stuten.vps;

import dev.stuten.vps.web.Routes;
import io.javalin.Javalin;

public class App {
    
    public static void main(String[] args) {
        int port = Integer.parseInt(
            System.getProperty("server.port", "8080")
        );

        Javalin app = Javalin.create(config -> {
            config.http.defaultContentType = "application/json";
        });

        Routes.register(app);

        System.out.println("%Mains");

        app.start(port);
    }
}
